# Generated by Django 3.1.5 on 2021-01-17 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='alcohol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Alcohol', to='selections.pumptoaliquid'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='mixer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mixer', to='selections.pumptoaliquid'),
        ),
    ]
