# Generated by Django 3.1.5 on 2021-01-17 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0002_auto_20210117_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength_name', models.CharField(max_length=50)),
                ('pump_turns', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='pumptoaliquid',
            name='pump_num',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
