# Generated by Django 3.1.5 on 2021-01-21 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0004_auto_20210120_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pumptoaliquid',
            name='liquid_type',
        ),
    ]
