# Generated by Django 3.1.5 on 2021-01-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0005_remove_pumptoaliquid_liquid_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumptoaliquid',
            name='liquid_type',
            field=models.CharField(choices=[('Alcohol', 'Alcohol'), ('Mixer', 'Mixer')], max_length=50, null=True),
        ),
    ]
